INSERT INTO todo_entry (id,
                        created_at,
                        title,
                        finished)

VALUES  (nextval('todo_entry_seq'), current_timestamp, 'Nakoupit potraviny', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Uklidit byt', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zavolat rodičům', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Dokončit projekt do práce', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Přečíst knihu', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Naplánovat dovolenou', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Jít na procházku', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Navštívit lékaře', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Opravit kolo', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Uvařit večeři', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Vyprat prádlo', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Napsat dopis', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít do banky', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zkontrolovat emaily', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Připravit prezentaci', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Jít do posilovny', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zalít květiny', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Opravit počítač', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Napsat článek', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na poštu', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Připravit oběd', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Udělat domácí úkol', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít do knihovny', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Vyčistit auto', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Napsat recenzi', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na nákup', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Připravit snídani', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na úřad', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Napsat zprávu', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na kávu s přáteli', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zkontrolovat auto', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Napsat blog', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Jít na běh', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Udělat nákup', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít do lékárny', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Připravit večeři', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na trh', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Uklidit garáž', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na cvičení', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Napsat knihu', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na koncert', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Připravit prezentaci', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na výstavu', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Udělat úkol', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na procházku', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Připravit oběd', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na úřad', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Napsat zprávu', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na kávu s přáteli', false),
        (nextval('todo_entry_seq'), current_timestamp, 'Zajít na nákup', false);
